title: mRemoteNG
description: The next generation of mRemote, open source, tabbed, multi-protocol, remote connections manager.
url: https://mremoteng.github.io
baseurl: 
repository: mRemoteNG/mRemoteNG.github.io
exclude: [README.md, CNAME, Gemfile, Gemfile.lock]
permalink: /posts/:categories/:year/:month/:day/:title/
paginate: 5
paginate_path: /posts/:num/
excerpt_separator: <!--more-->
logo: /favicon/256.png
twitter:
  username: mRemoteNG
github_alt:
  repository_url: https://github.com/mRemoteNG/mRemoteNG
  repository_nwo: mRemoteNG/mRemoteNG
  releases_url: https://github.com/mRemoteNG/mRemoteNG/releases
  issues_url: https://github.com/mRemoteNG/mRemoteNG/issues
  wiki_url: https://github.com/mRemoteNG/mRemoteNG/wiki

defaults:
  -
    scope:
      path: ''
    values:
      image: /favicon/256.png
  -
    scope:
      path: ''
      type: pages
    values:
      layout: default
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
